image: maven:3.8-openjdk-11

default:
  tags:
    - shelllocal

stages:
  - tests
#  - testAuthorization
#  - testChunkServers
#  - testClusters
#  - testEvents
#  - testISCSI
#  - testLicense
#  - testNodes
#  - testOvervies
#  - testS3
#  - testServices
#  - testSoftwareUpdate
#  - testStatistics
#  - testTasks
#  - testUser
  - allure

testAuthorization test:
  stage: tests
  allow_failure: true
  script: mvn -x test Authorization
  artifacts:
    paths:
      -target/allure-results

testChunkServers test:
  stage: tests
  allow_failure: true
  script: mvn -x test ChunkServers
  artifacts:
    paths:
      -target/allure-results

allure report:
  stage: allure
#  allow_failure: true
  script:
    - ./maven allure generate
    - - echo "Allure report live here - https://${CI_PROJECT_NAMESPACE}.${CI_PAGES_DOMAIN}/-/${CI_PROJECT_NAME}/-/jobs/${CI_JOB_ID}/artifacts/target/site/allure-maven-plugin/index.html"
  artifacts:
    when: always
    paths:
      - target/allure-report/*

